@startuml

title __MODEL's Class Diagram__\n

  namespace com.example.our_planner {
    namespace model {
      class com.example.our_planner.model.Comment {
          - date : String
          - message : String
          - user : String
          + Comment()
          + Comment()
          + getDate()
          + getMessage()
          + getUser()
          + setDate()
          + setMessage()
          + setUser()
          + toString()
      }
    }
  }
  

  namespace com.example.our_planner {
    namespace model {
      class com.example.our_planner.model.Event {
          {static} + eventsList : ArrayList<Event>
          - allDay : boolean
          - date : LocalDate
          - id : String
          - location : String
          - name : String
          - time : LocalTime
          + Event()
          + Event()
          {static} + eventsForDate()
          + getDate()
          + getId()
          + getLocation()
          + getName()
          + getTime()
          + isAllDay()
          + setAllDay()
          + setDate()
          + setLocation()
          + setName()
          + setTime()
      }
    }
  }
  

  namespace com.example.our_planner {
    namespace model {
      class com.example.our_planner.model.Group {
          - admins : Map<String, Boolean>
          - colours : Map<String, Integer>
          - details : String
          - events : ArrayList<Event>
          - id : String
          - participants : Map<String, User>
          - title : String
          + Group()
          + addEvent()
          + getAdmins()
          + getColours()
          + getDetails()
          + getEvents()
          + getId()
          + getParticipants()
          + getTitle()
          + removeEvent()
      }
    }
  }
  

  namespace com.example.our_planner {
    namespace model {
      class com.example.our_planner.model.Invitation {
          - author : String
          - groupId : String
          - title : String
          + Invitation()
          + getAuthor()
          + getGroupId()
          + getTitle()
      }
    }
  }
  

  namespace com.example.our_planner {
    namespace model {
      class com.example.our_planner.model.User {
          - username : String
          + User()
          + getUsername()
      }
    }
  }
  

  com.example.our_planner.model.Event .up.|> java.io.Serializable
  com.example.our_planner.model.Group .up.|> java.io.Serializable
  com.example.our_planner.model.User .up.|> java.io.Serializable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
