@startuml
hide empty members

class "Usuari" as Usuari {
  String : Nom
  String : Mail
  String : Contrassenya
  Image : Foto de Perfil
}

class "Event" as Event {
  String : Nom
  String : Descripció
  LocalDate : Data
  LocalTime : Hora d'Inici
  LocalTime : Hora de Final
}
class "Grup" as Grup {
  String : Nom
  String : Detalls
  Int : Color
  Int : Identificador
}

class "Admin" as Admin {
}

class "Invitació" as Invitació {
}

Usuari "1...*" -- "*" Event : Té >

Usuari "1...*" -- "*" Grup : Està Inscrit >

Event "*" -- "1" Grup : Pertany >

Usuari "1" -- "*" Invitació : Rep >

Admin "1" -- "*" Invitació : Envia >

Admin "1" -- "*" Grup : Crea

Admin "1" -- "*" Event : Crea >

Admin "1" -- "1" Usuari : Fa Admin >

Grup "1" -- "*" Invitació : Té Grup >

Usuari --> Admin: (Herència)

@enduml