@startuml
hide empty members


title __OUR_PLANNER's Model Domain__\n
left to right direction

class "Usuari" as Usuari {
  String : Nom
  String : Email
  String : Contrasenya
  Image : Foto de Perfil
}

class "Event" as Event {
  String : Nom
  String : Descripció
  LocalDate : Data
  LocalTime : Hora d'Inici
  LocalTime : Hora de Final
}

class "Color" as Color {
  int : Transparència
  int : R
  int : G
  int : B
}

class "Grup" as Grup {
  String : Identificador
  String : Nom
  String : Detalls
}

class "Admin" as Admin {
}

class "Invitació" as Invitació {
}

Usuari  "*" -- "*" Color : Escull >

note "Cada usuari escull un únic color per grup al que està inscrit" as nota
nota .- Color

Color "*" -- "*" Grup : Referent a >

Usuari "1...*" -- "*" Event : Té >

Usuari "1...*" -- "*" Grup : Està Inscrit >

Event "*" -- "1" Grup : Pertany >

Usuari "1" -- "*" Invitació : Rep >

Admin "1" -- "*" Invitació : Envia >

Admin "1" -- "1..*" Grup : Gestiona >

Admin "1" -- "*" Event : Gestiona >

Admin "*" -- "*" Usuari : Gestiona >

Grup "1" -- "*" Invitació : Associada A <

Usuari <|-- Admin

@enduml