@startuml

title __OUR_PLANNER's Class Diagram__\n
left to right direction

  namespace com.example.our_planner {
    abstract class com.example.our_planner.DataBaseAdapter {
    }
  }




    namespace com.example.our_planner {
      namespace ui.calendar {
        namespace comments {
          class com.example.our_planner.ui.calendar.comments.AdapterComments {

          }
        }
      }
    }


    namespace com.example.our_planner {
      namespace ui.calendar {
        namespace comments {
          class com.example.our_planner.ui.calendar.comments.AdapterComments.ViewHolderComments {

          }
        }
      }
    }


    namespace com.example.our_planner {
      namespace ui.calendar {
        namespace comments {
          class com.example.our_planner.ui.calendar.comments.CommentsActivity {

          }
        }
      }
    }


    namespace com.example.our_planner {
      namespace ui.calendar {
        namespace comments {
          class com.example.our_planner.ui.calendar.comments.CommentsViewModel {
              ~ comments : MutableLiveData<ArrayList<Comment>>

          }
        }
      }
    }


    com.example.our_planner.ui.calendar.comments.AdapterComments +-down- com.example.our_planner.ui.calendar.comments.AdapterComments.ViewHolderComments
    com.example.our_planner.ui.calendar.comments.CommentsViewModel .up.|> com.example.our_planner.DataBaseAdapter.CommentInterface



  namespace com.example.our_planner {
    namespace ui.calendar {
      class com.example.our_planner.ui.calendar.AdapterCalendarGroups {

      }
    }
  }


  namespace com.example.our_planner {
    namespace ui.calendar {
      class com.example.our_planner.ui.calendar.AdapterCalendarGroups.ViewHolderCalendarGroups {

      }
    }
  }


  namespace com.example.our_planner {
    namespace ui.calendar {
      class com.example.our_planner.ui.calendar.CalendarAdapter {

      }
    }
  }


  namespace com.example.our_planner {
    namespace ui.calendar {
      interface com.example.our_planner.ui.calendar.CalendarAdapter.OnItemListener {

      }
    }
  }


  namespace com.example.our_planner {
    namespace ui.calendar {
      class com.example.our_planner.ui.calendar.CalendarFragment {

      }
    }
  }


  namespace com.example.our_planner {
    namespace ui.calendar {
      class com.example.our_planner.ui.calendar.CalendarGroupsFragment {

      }
    }
  }


  namespace com.example.our_planner {
    namespace ui.calendar {
      class com.example.our_planner.ui.calendar.CalendarUtils {

      }
    }
  }


  namespace com.example.our_planner {
    namespace ui.calendar {
      class com.example.our_planner.ui.calendar.CalendarViewHolder {

      }
    }
  }


  namespace com.example.our_planner {
    namespace ui.calendar {
      class com.example.our_planner.ui.calendar.CalendarViewModel {
          - mGroups : MutableLiveData<ArrayList<Group>>

      }
    }
  }


  namespace com.example.our_planner {
    namespace ui.calendar {
      class com.example.our_planner.ui.calendar.CreateEventActivity {

      }
    }
  }


  namespace com.example.our_planner {
    namespace ui.calendar {
      class com.example.our_planner.ui.calendar.CreateEventActivityViewModel {
      }
    }
  }


  namespace com.example.our_planner {
    namespace ui.calendar {
      class com.example.our_planner.ui.calendar.EditEventActivity {

      }
    }
  }


  namespace com.example.our_planner {
    namespace ui.calendar {
      class com.example.our_planner.ui.calendar.EventAdapter {

      }
    }
  }


  namespace com.example.our_planner {
    namespace ui.calendar {
      class com.example.our_planner.ui.calendar.EventAdapter.ViewHolderEvents {

      }
    }
  }


  namespace com.example.our_planner {
    namespace ui.calendar {
      class com.example.our_planner.ui.calendar.MonthCalendarFragment {

      }
    }
  }


  namespace com.example.our_planner {
    namespace ui.calendar {
      class com.example.our_planner.ui.calendar.WeekCalendarFragment {

      }
    }
  }


  com.example.our_planner.ui.calendar.AdapterCalendarGroups +-down- com.example.our_planner.ui.calendar.AdapterCalendarGroups.ViewHolderCalendarGroups
  com.example.our_planner.ui.calendar.CalendarAdapter o-- com.example.our_planner.ui.calendar.CalendarAdapter.OnItemListener : onItemListener
  com.example.our_planner.ui.calendar.CalendarAdapter +-down- com.example.our_planner.ui.calendar.CalendarAdapter.OnItemListener
  com.example.our_planner.ui.calendar.CalendarViewHolder o-- com.example.our_planner.ui.calendar.CalendarAdapter.OnItemListener : onItemListener
  com.example.our_planner.ui.calendar.CalendarViewModel .up.|> com.example.our_planner.DataBaseAdapter.GroupInterface
  com.example.our_planner.ui.calendar.EventAdapter +-down- com.example.our_planner.ui.calendar.EventAdapter.ViewHolderEvents
  com.example.our_planner.ui.calendar.MonthCalendarFragment .up.|> com.example.our_planner.ui.calendar.CalendarAdapter.OnItemListener
  com.example.our_planner.ui.calendar.WeekCalendarFragment .up.|> com.example.our_planner.ui.calendar.CalendarAdapter.OnItemListener



  namespace com.example.our_planner {
    namespace ui.groups {
      class com.example.our_planner.ui.groups.AdapterGroups {

      }
    }
  }


  namespace com.example.our_planner {
    namespace ui.groups {
      class com.example.our_planner.ui.groups.AdapterGroups.ViewHolderGroups {

      }
    }
  }


  namespace com.example.our_planner {
    namespace ui.groups {
      class com.example.our_planner.ui.groups.AdapterParticipants {

      }
    }
  }


  namespace com.example.our_planner {
    namespace ui.groups {
      class com.example.our_planner.ui.groups.AdapterParticipants.ViewHolderParticipants {

      }
    }
  }


  namespace com.example.our_planner {
    namespace ui.groups {
      class com.example.our_planner.ui.groups.AdapterParticipantsInvite {

      }
    }
  }


  namespace com.example.our_planner {
    namespace ui.groups {
      class com.example.our_planner.ui.groups.AdapterParticipantsInvite.ViewHolderParticipantsInvite {

      }
    }
  }


  namespace com.example.our_planner {
    namespace ui.groups {
      class com.example.our_planner.ui.groups.CreateGroupActivity {

      }
    }
  }


  namespace com.example.our_planner {
    namespace ui.groups {
      class com.example.our_planner.ui.groups.CreateGroupActivityViewModel {
          - mRegistered : MutableLiveData<Boolean>
          - mToast : MutableLiveData<String>

      }
    }
  }


  namespace com.example.our_planner {
    namespace ui.groups {
      class com.example.our_planner.ui.groups.EditGroupActivity {

      }
    }
  }


  namespace com.example.our_planner {
    namespace ui.groups {
      class com.example.our_planner.ui.groups.EditGroupActivityViewModel {
          - mRegistered : MutableLiveData<Boolean>
          - mToast : MutableLiveData<String>
      }
    }
  }


  namespace com.example.our_planner {
    namespace ui.groups {
      class com.example.our_planner.ui.groups.GroupsFragment {

      }
    }
  }


  namespace com.example.our_planner {
    namespace ui.groups {
      class com.example.our_planner.ui.groups.GroupsViewModel {
          - mGroups : MutableLiveData<ArrayList<Group>>
          - mToast : MutableLiveData<String>
      }
    }
  }


  com.example.our_planner.ui.groups.AdapterGroups +-down- com.example.our_planner.ui.groups.AdapterGroups.ViewHolderGroups
  com.example.our_planner.ui.groups.AdapterParticipants +-down- com.example.our_planner.ui.groups.AdapterParticipants.ViewHolderParticipants
  com.example.our_planner.ui.groups.AdapterParticipantsInvite +-down- com.example.our_planner.ui.groups.AdapterParticipantsInvite.ViewHolderParticipantsInvite
  com.example.our_planner.ui.groups.CreateGroupActivity o-- com.example.our_planner.ui.groups.CreateGroupActivityViewModel : viewModel
  com.example.our_planner.ui.groups.CreateGroupActivityViewModel .up.|> com.example.our_planner.DataBaseAdapter.EmailCheckerInterface
  com.example.our_planner.ui.groups.EditGroupActivity o-- com.example.our_planner.ui.groups.EditGroupActivityViewModel : viewModel
  com.example.our_planner.ui.groups.EditGroupActivityViewModel .up.|> com.example.our_planner.DataBaseAdapter.EmailCheckerInterface
  com.example.our_planner.ui.groups.GroupsFragment o-- com.example.our_planner.ui.groups.GroupsViewModel : viewModel
  com.example.our_planner.ui.groups.GroupsViewModel .up.|> com.example.our_planner.DataBaseAdapter.DBInterface
  com.example.our_planner.ui.groups.GroupsViewModel .up.|> com.example.our_planner.DataBaseAdapter.GroupInterface

  namespace com.example.our_planner {
    namespace ui.invitations {
      class com.example.our_planner.ui.invitations.AdapterInvitations {

      }
    }
  }


  namespace com.example.our_planner {
    namespace ui.invitations {
      class com.example.our_planner.ui.invitations.AdapterInvitations.ViewHolderInvitations {

      }
    }
  }


  namespace com.example.our_planner {
    namespace ui.invitations {
      class com.example.our_planner.ui.invitations.InvitationsFragment {

      }
    }
  }


  namespace com.example.our_planner {
    namespace ui.invitations {
      class com.example.our_planner.ui.invitations.InvitationsViewModel {
          - mInvitations : MutableLiveData<ArrayList<Invitation>>
          - mToast : MutableLiveData<String>

      }
    }
  }


  com.example.our_planner.ui.invitations.AdapterInvitations +-down- com.example.our_planner.ui.invitations.AdapterInvitations.ViewHolderInvitations
  com.example.our_planner.ui.invitations.InvitationsFragment o-- com.example.our_planner.ui.invitations.InvitationsViewModel : viewModel
  com.example.our_planner.ui.invitations.InvitationsViewModel .up.|> com.example.our_planner.DataBaseAdapter.InvitationInterface


  namespace com.example.our_planner {
    namespace ui.settings {
      class com.example.our_planner.ui.settings.SettingsFragment {
      }
    }
  }


  namespace com.example.our_planner {
    namespace ui.settings {
      class com.example.our_planner.ui.settings.SettingsViewModel {
          - mText : MutableLiveData<String>
      }
    }
  }




  namespace com.example.our_planner {
    namespace ui.user {
      class com.example.our_planner.ui.user.ForgotPasswordActivity {

      }
    }
  }


  namespace com.example.our_planner {
    namespace ui.user {
      class com.example.our_planner.ui.user.LoginActivity {

      }
    }
  }


  namespace com.example.our_planner {
    namespace ui.user {
      class com.example.our_planner.ui.user.LoginActivityViewModel {
          - mToast : MutableLiveData<String>

      }
    }
  }


  namespace com.example.our_planner {
    namespace ui.user {
      class com.example.our_planner.ui.user.RegisterActivity {

      }
    }
  }


  namespace com.example.our_planner {
    namespace ui.user {
      class com.example.our_planner.ui.user.RegisterActivityViewModel {
          - mToast : MutableLiveData<String>
      }
    }
  }


  com.example.our_planner.ui.user.ForgotPasswordActivity .up.|> com.example.our_planner.DataBaseAdapter.DBInterface
  com.example.our_planner.ui.user.LoginActivity o-- com.example.our_planner.ui.user.LoginActivityViewModel : viewModel
  com.example.our_planner.ui.user.LoginActivityViewModel .up.|> com.example.our_planner.DataBaseAdapter.DBInterface
  com.example.our_planner.ui.user.RegisterActivity o-- com.example.our_planner.ui.user.RegisterActivityViewModel : viewModel
  com.example.our_planner.ui.user.RegisterActivityViewModel .up.|> com.example.our_planner.DataBaseAdapter.DBInterface














  namespace com.example.our_planner {
    interface com.example.our_planner.DataBaseAdapter.CommentInterface {
    }
  }
  

  namespace com.example.our_planner {
    interface com.example.our_planner.DataBaseAdapter.DBInterface {
    }
  }
  

  namespace com.example.our_planner {
    interface com.example.our_planner.DataBaseAdapter.EmailCheckerInterface {
    }
  }
  

  namespace com.example.our_planner {
    interface com.example.our_planner.DataBaseAdapter.GroupInterface {

    }
  }
  

  namespace com.example.our_planner {
    interface com.example.our_planner.DataBaseAdapter.InvitationInterface {
    }
  }
  

  namespace com.example.our_planner {
    class com.example.our_planner.NavigationDrawer {

    }
  }
  

  com.example.our_planner.DataBaseAdapter +-down- com.example.our_planner.DataBaseAdapter.CommentInterface
  com.example.our_planner.DataBaseAdapter +-down- com.example.our_planner.DataBaseAdapter.DBInterface
  com.example.our_planner.DataBaseAdapter +-down- com.example.our_planner.DataBaseAdapter.EmailCheckerInterface
  com.example.our_planner.DataBaseAdapter +-down- com.example.our_planner.DataBaseAdapter.GroupInterface
  com.example.our_planner.DataBaseAdapter +-down- com.example.our_planner.DataBaseAdapter.InvitationInterface

  com.example.our_planner.ui.calendar.comments.CommentsActivity --> com.example.our_planner.ui.calendar.comments.CommentsViewModel
  com.example.our_planner.ui.calendar.comments.CommentsViewModel --> com.example.our_planner.DataBaseAdapter
  com.example.our_planner.ui.calendar.CalendarFragment --> com.example.our_planner.ui.calendar.comments.CommentsActivity
  com.example.our_planner.ui.calendar.CalendarViewModel --> com.example.our_planner.DataBaseAdapter
  com.example.our_planner.ui.calendar.EventsViewModel --> com.example.our_planner.DataBaseAdapter
  com.example.our_planner.ui.groups.AdapterGroups --> com.example.our_planner.DataBaseAdapter
  com.example.our_planner.ui.groups.AdapterParticipants --> com.example.our_planner.DataBaseAdapter
  com.example.our_planner.ui.groups.CreateGroupActivityViewModel --> com.example.our_planner.DataBaseAdapter
  com.example.our_planner.ui.groups.EditGroupActivityViewModel --> com.example.our_planner.DataBaseAdapter
  com.example.our_planner.ui.groups.GroupsViewModel --> com.example.our_planner.DataBaseAdapter
  com.example.our_planner.ui.invitations.AdapterInvitations --> com.example.our_planner.DataBaseAdapter
  com.example.our_planner.ui.invitations.InvitationsViewModel --> com.example.our_planner.DataBaseAdapter
  com.example.our_planner.ui.settings.SettingsFragment --> com.example.our_planner.NavigationDrawer
  com.example.our_planner.ui.settings.SettingsFragment --> com.example.our_planner.DataBaseAdapter
  com.example.our_planner.ui.user.ForgotPasswordActivity --> com.example.our_planner.DataBaseAdapter
  com.example.our_planner.ui.user.LoginActivity --> com.example.our_planner.NavigationDrawer
  com.example.our_planner.ui.user.LoginActivityViewModel --> com.example.our_planner.DataBaseAdapter
  com.example.our_planner.ui.user.RegisterActivity --> com.example.our_planner.NavigationDrawer
  com.example.our_planner.ui.user.RegisterActivityViewModel --> com.example.our_planner.DataBaseAdapter



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
