@startuml

title __OUR_PLANNER's Class Diagram__\n

  namespace com.example.our_planner {
    abstract class com.example.our_planner.DataBaseAdapter {
        {static} - byteArray : byte[]
        {static} - db : FirebaseFirestore
        {static} - groupInterfaces : List<GroupInterface>
        {static} - invitationInterface : InvitationInterface
        {static} - mAuth : FirebaseAuth
        {static} - registrationCompleted : boolean
        {static} - rtdb : FirebaseDatabase
        {static} - storage : FirebaseStorage
        {static} - user : FirebaseUser
        {static} + acceptInvitation()
        {static} + alreadyLoggedIn()
        {static} + checkRegistered()
        {static} + createEvent()
        {static} + createGroup()
        {static} + deleteEvent()
        {static} + deleteInvitation()
        {static} + editEvent()
        {static} + editGroup()
        {static} + forgotPassword()
        {static} + getByteArray()
        {static} + getEmail()
        {static} + getUserName()
        {static} + isRegistrationCompleted()
        {static} + leaveGroup()
        {static} + loadComments()
        {static} + loadGroups()
        {static} + loadInvitations()
        {static} + logOut()
        {static} + login()
        {static} + postComment()
        {static} + register()
        {static} + setProfilePicture()
        {static} + subscribeGroupObserver()
        {static} + subscribeInvitationObserver()
        {static} + updateProfilePicture()
        {static} - deleteGroupInvitations()
        {static} - loadEvents()
        {static} - mapEventDocument()
        {static} - mapGroupDocument()
        {static} - modifyInvitations()
        {static} - sendInvitation()
        {static} - sendInvitations()
    }
  }
  

  namespace com.example.our_planner {
    interface com.example.our_planner.DataBaseAdapter.CommentInterface {
        {abstract} + addComment()
    }
  }
  

  namespace com.example.our_planner {
    interface com.example.our_planner.DataBaseAdapter.DBInterface {
        {abstract} + setToast()
    }
  }
  

  namespace com.example.our_planner {
    interface com.example.our_planner.DataBaseAdapter.EmailCheckerInterface {
        {abstract} + setChecked()
    }
  }
  

  namespace com.example.our_planner {
    interface com.example.our_planner.DataBaseAdapter.GroupInterface {
        {abstract} + update()
    }
  }
  

  namespace com.example.our_planner {
    interface com.example.our_planner.DataBaseAdapter.InvitationInterface {
        {abstract} + update()
    }
  }
  

  namespace com.example.our_planner {
    class com.example.our_planner.NavigationDrawer {
        - appBarConfiguration : AppBarConfiguration
        - drawerLayout : DrawerLayout
        - navController : NavController
        - navigationView : NavigationView
        - profilePictureND : ImageView
        - toolbar : Toolbar
        + onCreateOptionsMenu()
        + onNavigationItemSelected()
        + onSupportNavigateUp()
        + updateProfilePicture()
        # onCreate()
    }
  }
  

  com.example.our_planner.DataBaseAdapter +-down- com.example.our_planner.DataBaseAdapter.CommentInterface
  com.example.our_planner.DataBaseAdapter +-down- com.example.our_planner.DataBaseAdapter.DBInterface
  com.example.our_planner.DataBaseAdapter +-down- com.example.our_planner.DataBaseAdapter.EmailCheckerInterface
  com.example.our_planner.DataBaseAdapter +-down- com.example.our_planner.DataBaseAdapter.GroupInterface
  com.example.our_planner.DataBaseAdapter +-down- com.example.our_planner.DataBaseAdapter.InvitationInterface
  com.example.our_planner.NavigationDrawer .up.|> com.google.android.material.navigation.NavigationView.OnNavigationItemSelectedListener
  com.example.our_planner.NavigationDrawer -up-|> androidx.appcompat.app.AppCompatActivity


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
